### PR TITLE
bash auto-completion for config file

### PR DESCRIPTION
**Pull request by Mortezaipo**
Just need to copy "ugtrain" file from "extra/" directory to "/etc/bash_completion.d/"
Issue: #22

### CODE REVIEW

**Comment by Mortezaipo** [comment]
It needs update for empty dir

**Comment by sriemer** [comment]
Thanks, this looks quite similar to what I've put together as well. I thought that it would be easier. Thanks for confirming that it has to be done like this. It is possible to change commits under rewiew in a PR by forcefully pushing your branch with a replacement commit.
I'd like to see this in src/bash_completion/ to make it clear what this is about. Without the autotools deployment via `make install` this is still incomplete.

**Comment by Mortezaipo** [comment]
I will update autotools and auto-completion directory.

**Comment by sriemer** [comment]
I've implemented this myself in the meanwhile. Thanks for your help @Mortezaipo!

**Comment by sriemer** [comment]
It would be really appreciated if you could verify the final commits. But I'm confident that they will work for you as well.

**Pull request closed without merging**
